### PR TITLE
feat(devex): Add devcontainer configuration and dotenv support

### PR DESCRIPTION
**Pull request by ahanafy**
Introduce a development container setup for easier development and enhance README files with setup instructions. Implement dotenv support for managing environment variables and remove submodule references, updating requirements to point to the main branch of the open-mpic-core-python repository using direct github sources (until open-mpic-core is available via pypi)

### CODE REVIEW

**Comment by sciros** [comment]
Regarding dotenv usage, is the idea to mount fully-defined config files as part of starting the docker containers, overriding the default ones in the repo?

**Comment by ahanafy** [comment]
> @ahanafy Regarding dotenv usage, is the idea to mount fully-defined config files as part of starting the docker containers, overriding the default ones in the repo?

Yes exactly. The ones that are there are just examples. In a container we would mount real files with real values. Right now I've put the real keys but fake values. We could either replace the fake values with "sane defaults" or empty values so that it is more obvious the existing files are not meant to be used as-is.

**Comment by birgelee** [comment]
Did a review. Overall I think its all good. One thing that confuse me was the dev container was for python 3.12 but the rest of the project (including the new .python-version files) specify 3.11. I am generally just using 3.11 across the board so I changed it. I also didn't really like the Foo Bar placeholder values. I worry someone will just run the README instructions and be like "it doesn't work!" I made the placeholder values even more placeholder looking and updated the readme to clarify it will not run as is. @ahanafy let me know if you are good with these changes and I will merge in.

**Comment by ahanafy** [comment]
> Did a review. Overall I think its all good. One thing that confuse me was the dev container was for python 3.12 but the rest of the project (including the new .python-version files) specify 3.11. I am generally just using 3.11 across the board so I changed it. I also didn't really like the Foo Bar placeholder values. I worry someone will just run the README instructions and be like "it doesn't work!" I made the placeholder values even more placeholder looking and updated the readme to clarify it will not run as is. @ahanafy let me know if you are good with these changes and I will merge in.

Those changes are great, thanks @birgelee

**Pull request merged**
